
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "e18deac4-0606-4b37-b17d-1092680584b3"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "35c5a4b9-3705-4d33-80e3-306bd9357dcd",
    "account_id_to": "9ff99e13-200e-463c-b453-62dace6767a2",
    "amount": 1
}